# Generated by Django 6.0.2 on 2026-02-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('RONDA', 'Ronda programada'), ('WSP', 'Whatsapp'), ('CALL', 'Llamado'), ('TPROG', 'Trabajo programado'), ('FRACTTAL', 'Fracttal'), ('RADIO', 'Radio'), ('MAIL', 'Correo electrónico')], max_length=20)),
                ('numero_orden', models.CharField(blank=True, max_length=100, null=True)),
                ('solicitante', models.CharField(choices=[('HOTELERIA', 'Hotelería'), ('SERV_CLINICA', 'Servicios clínica'), ('EXP_PACIENTE', 'Experiencia de pacientes'), ('SUP_CLINICA', 'Supervisión clínica'), ('CLIMA', 'Climatización'), ('TPROG', 'Trabajo programado'), ('EQ_MED', 'Equipos médicos')], max_length=50)),
                ('torre', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('CDA', 'CDA'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('SUBESTACIONES', 'Subestaciones'), ('UPS', 'UPS'), ('Z_CRITICAS', 'Zonas críticas')], max_length=20)),
                ('piso', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('1SUB', '1° sub'), ('2SUB', '2° sub'), ('3SUB', '3° sub'), ('4SUB', '4° sub'), ('5SUB', '5° sub'), ('AZOTEA', 'Azotea')], max_length=20)),
                ('servicio', models.CharField(max_length=150)),
                ('habitacion_box', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° habitación / Box')),
                ('tipo_trabajo', models.CharField(choices=[('ACCESO', 'Acceso'), ('CABECERA', 'Cabecera'), ('CIRCUITOS', 'Circuitos'), ('CLAVE_ROJA', 'Clave roja (humo/fuego)'), ('CORTE_COMP', 'Corte compañía'), ('ARTEFACTO', 'Artefacto'), ('LEVANTAMIENTO', 'Levantamiento / identificación'), ('LUMINARIA', 'Luminaria'), ('MANTENCION', 'Mantención'), ('PROTOCOLOS', 'Protocolos'), ('PRUEBA_VACIO', 'Prueba en vacío'), ('REVISION', 'Revisión / medición'), ('RONDA', 'Ronda'), ('TABLEROS', 'Tableros'), ('TIMBRE', 'Timbre')], max_length=30)),
                ('numero_circuito', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° circuito')),
                ('cantidad_luminaria', models.IntegerField(blank=True, null=True)),
                ('tipo_luminaria', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('REALIZADO', 'Realizado'), ('PENDIENTE', 'Pendiente')], max_length=20)),
                ('turno', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
