# Generated by Django 6.0.2 on 2026-02-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='evento',
            name='canal',
            field=models.CharField(choices=[('RONDA', 'Ronda programada'), ('WSP', 'Whatsapp'), ('CALL', 'Llamado'), ('TPROG', 'Trabajo programado'), ('FRACTTAL', 'Fracttal'), ('RADIO', 'Radio'), ('MAIL', 'Correo electrónico')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('REALIZADO', 'Realizado'), ('PENDIENTE', 'Pendiente')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='servicio',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_luminaria',
            field=models.CharField(blank=True, choices=[('18W', '18W'), ('60X60', '60x60'), ('AMPOLLETA', 'Ampolleta'), ('DICROICO', 'Dicroicos'), ('CPI', 'Foco CPI'), ('TUBO_LED', 'Tubo LED')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_trabajo',
            field=models.CharField(choices=[('ACCESO', 'Acceso'), ('CABECERA', 'Cabecera'), ('CIRCUITOS', 'Circuitos'), ('CLAVE_ROJA', 'Clave roja (humo/fuego)'), ('CORTE_COMP', 'Corte compañía'), ('ARTEFACTO', 'Artefacto'), ('LEVANTAMIENTO', 'Levantamiento / identificación'), ('LUMINARIA', 'Luminaria'), ('MANTENCION', 'Mantención'), ('PROTOCOLOS', 'Protocolos'), ('PRUEBA_VACIO', 'Prueba en vacío'), ('REVISION', 'Revisión / medición'), ('RONDA', 'Ronda'), ('TABLEROS', 'Tableros'), ('TIMBRE', 'Timbre')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='evento',
            name='torre',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('CDA', 'CDA'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('SUBESTACIONES', 'Subestaciones'), ('UPS', 'UPS'), ('Z_CRITICAS', 'Zonas críticas')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='turno',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5')], db_index=True, max_length=2),
        ),
    ]
