# Generated by Django 6.0.2 on 2026-02-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_options_alter_evento_canal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='piso',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('1SUB', '1° sub'), ('2SUB', '2° sub'), ('3SUB', '3° sub'), ('4SUB', '4° sub'), ('5SUB', '5° sub'), ('AZOTEA', 'Azotea')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='servicio',
            field=models.CharField(choices=[('BANCO_SANGRE', 'Banco de sangre'), ('BANO_VEST', 'Baño / vestidores'), ('BODEGA', 'Bodega'), ('CAFETERIA', 'Cafetería'), ('CALL_CENTER', 'Call center'), ('CASINO', 'Casino'), ('CIC', 'Centro integral del cáncer'), ('CLIMA_AZOTEA', 'Clima azotea'), ('CMA', 'CMA'), ('CONSULTA_MED', 'Consulta médica'), ('COR_INTENSIVA', 'Coronaria intensiva'), ('DIALISIS', 'Diálisis'), ('ESTACIONAMIENTO', 'Estacionamiento'), ('ESTERILIZACION', 'Esterilización'), ('FARMACIA', 'Farmacia'), ('FLEISCHMANN', 'Fleischmann'), ('GERENCIA', 'Gerencia'), ('GIM_KINE', 'Gimnasio / kinesiología'), ('HALL_ASC', 'Hall de ascensores'), ('IMAGENES', 'Imágenes'), ('LABORATORIO', 'Laboratorio'), ('MED_PREVENTIVA', 'Medicina preventiva'), ('MQ', 'MQ'), ('NEONATOLOGIA', 'Neonatología'), ('NEUROLOGIA', 'Neurología'), ('OF_ADM', 'Oficina administrativa'), ('PABELLON', 'Pabellón'), ('PARKING', 'Párking'), ('PASILLO', 'Pasillo general'), ('REAS', 'REAS'), ('RESIDENCIA', 'Residencia'), ('SALA_ESPERA', 'Sala de espera'), ('SEDILE', 'Sedile'), ('SHAFT_TISAL', 'Shaft TISAL'), ('SUBGERENCIA', 'Subgerencia'), ('UCI', 'UCI'), ('UPC_PED', 'UPC pediátrico'), ('UPS', 'UPS'), ('URGENCIA', 'Urgencia'), ('UTI', 'Uti'), ('VITAMINA', 'Vitamina')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha_creacion'], name='eventos_eve_fecha_c_9ad9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['tipo_trabajo'], name='eventos_eve_tipo_tr_0b45cc_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['torre'], name='eventos_eve_torre_469724_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['servicio'], name='eventos_eve_servici_f94dae_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['estado'], name='eventos_eve_estado_6b5412_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['turno'], name='eventos_eve_turno_d975ae_idx'),
        ),
    ]
