# Generated by Django 6.0.2 on 2026-02-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_piso_alter_evento_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='piso',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('1SUB', '1° sub'), ('2SUB', '2° sub'), ('3SUB', '3° sub'), ('4SUB', '4° sub'), ('5SUB', '5° sub'), ('AZOTEA', 'Azotea')], max_length=20, null=True),
        ),
    ]
