# Generated by Django 6.0.2 on 2026-02-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='turno',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5')], db_index=True, max_length=2, null=True),
        ),
    ]
