# Generated by Django 6.0.2 on 2026-02-26 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_evento_turno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoFracttal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriccion', models.CharField(max_length=255, verbose_name='Restricción')),
                ('encargado_area', models.CharField(blank=True, max_length=120, verbose_name='Encargado del área')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_fracttal_creados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_fracttal', to='eventos.evento', verbose_name='Evento asociado')),
            ],
            options={
                'verbose_name': 'Seguimiento Fracttal',
                'verbose_name_plural': 'Seguimientos Fracttal',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_creacion'], name='eventos_seg_fecha_c_a8dc8d_idx')],
            },
        ),
    ]
